{{- if eq .Values.tls.enabled true }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.tls.default_issuer_name }}
spec:
  acme:
    server: {{ .Values.tls.server }}
    email: {{ .Values.tls.acme_registration_email }}
    privateKeySecretRef:
      name: {{ .Values.tls.secret_reference }}
    solvers:
    - http01: {}
{{- end -}}
