{{- if eq .Values.ingress.enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{  template "fullname" . }}-ingress-rules
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ .Values.tls.secret_reference }}
      hosts:
        - {{ .Values.fn_api.service.ingress_hostname }}
        - {{ .Values.fn_lb_runner.service.ingress_hostname }}
  {{- end }}
  rules:
    - host: {{ .Values.fn_api.service.ingress_hostname }}
      http:
        paths:
        - pathType: ImplementationSpecific
          path: /
          backend:
            service:
              name: {{ template "fullname" . }}-api
              port: 
                number: {{ .Values.fn_api.service.port }}
    - host: {{ .Values.fn_lb_runner.service.ingress_hostname }}
      http:
        paths:
        - pathType: ImplementationSpecific
          path: /
          backend:
            service:
              name: {{ template "fullname" . }}-lb
              port: 
                number: {{ .Values.fn_lb_runner.service.port }}
    - host: {{ .Values.ui.service.ingress_hostname }}
      http:
        paths:
        - pathType: ImplementationSpecific
          path: /
          backend:
            service:
              name: {{ template "fullname" . }}-ui
              port: 
                number: {{ .Values.ui.service.port }}
    - host: {{ .Values.flow.service.ingress_hostname }}
      http:
        paths:
        - pathType: ImplementationSpecific
          path: /
          backend:
            service:
              name: {{ template "fullname" . }}-flow
              port: 
                number: {{ .Values.flow.service.port }}
{{- end }}
